### ISSUE TITLE
基于Zrender渲染的ECharts图表库是否可以在QML当中使用呢？

### ISSUE THREAD

**Issue by toby20130333** [cwc1987/qml_js_test#1]
百度开发了一款基于zrender的echarts图表库,想问下您是否可以在QML当中使用，如果可以的话 是否需要修改大量的源码呢？

**Comment by cwc1987** [comment]
尝试过使用QML移植，部分涉及到html的css和document操作需要适配，由于本人不太会前段开发，你看到的github上的库也属于尝试阶段，不过需要移植echarts，首先需要移植zrender，目前由于工作比较忙，还没有时间研究，不好意思，不能给你太多帮助
来自我的华为手机
